version: '3.8'
services:
  aurras-event-feed-substrate:
    image: hugobyte/aurras-event-feed-substrate:0.1.3
    container_name: aurras-event-feed-substrate
    networks:
      - gateway
    external_links:
      - kafka:kafka.docker
      - apigateway:apigateway.docker
    env_file:
      - ./local.env
    volumes:
      - ./logs:/logs
      - ./config:/config

networks:
  default:
    name: aurras
    driver: bridge
  gateway:
    name: gateway
    driver: bridge
