version: '3.5'
services:
  aurras-event-feed-substrate:
    build: aurras-event-feed-substrate-js
    container_name: aurras-event-feed-substrate
    networks:
      - gateway
    external_links:
      - apigateway:apigateway.docker
    env_file:
      - ./local.env
    volumes:
      - ./logs:/logs
      - ./config:/config

networks:
    default:
      name: aurras
      driver: bridge
    gateway:
      name: gateway
      external: true   