version: '3.5'
services:
  db:
    image: apache/couchdb:2.3
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    volumes:
      - ./data/couchdb:/opt/couchdb/data:rw

  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      ZOO_MY_ID: 1
  
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    links:
      - zookeeper
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka:rw

  kafka-rest:
    image: confluentinc/cp-kafka-rest:3.3.1
    hostname: kafka-rest
    environment:
      - ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT="*"
      - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_REST_HOST_NAME=kafka-rest
      - KAFKA_REST_LISTENERS=http://kafka-rest:8082
      - KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS=30000
      - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
    links:
      - zookeeper
      - kafka
    depends_on:
      - zookeeper
      - kafka

  kafka-topics-ui:
      image: landoop/kafka-topics-ui:0.9.3
      environment:
        - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
        - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
        - PROXY=true
      ports:
        - 8001:8000
      links:
        - kafka
        - kafka-rest

  redis:
    image: redis:2.8
    ports:
      - "6379:6379"

couchdb-setup:
    image: ddragosd/ansible:2.4.0.0-debian8
    working_dir: /openwhisk/ansible
    command: /bin/sh -c "ansible-playbook setup.yml >> /logs/couchdb-setup.log 2>&1 && ansible-playbook couchdb.yml --tags=ini >> /logs/couchdb-setup.log 2>&1 && ansible-playbook initdb.yml wipe.yml -e db_host=db.docker -e openwhisk_home=/openwhisk -e db_prefix=local_ >> /logs/couchdb-setup.log 2>&1"
    links:
      - db:db.docker
    depends_on:
      - db
    restart: "no"  
    volumes:
      - ./logs:/logs
      - ./config/ansible:/openwhisk/ansible